#name: devops test
#
#on:
#  push:
#    branches: [ main ]
#
#jobs:
#  deploy:
#    name: Deploy to EC2
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: get code from github
#      uses: appleboy/ssh-action@v1.0.3
#      with:
#        host: ${{ secrets.REMOTE_HOST }}
#        username: ${{ secrets.REMOTE_USER }}
#        key: ${{ secrets.SSH_KEY }}
#        port: ${{ secrets.REMOTE_PORT }}
#        script: |
#          echo test > /tmp/abcd

name: devops test

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          source: "build/libs/practice240809-0.0.1-SNAPSHOT.jar"
#target은 경로를 적어줘야하는데 파일이름을 적었어서 에러가 나는거였음
          target: "build/libs/practice240809-0.0.1-SNAPSHOT.jar"

      - name: restart spring project
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            rm -rf /home/ubuntu/practice240809
            git clone https://github.com/choijw1116/practice240809.git
            bash /home/ubuntu/practice240809/deployment.sh